export const IPC = {
  CONNECTION_ADD: 'connection:add',
  CONNECTION_REMOVE: 'connection:remove',
  CONNECTION_UPDATE: 'connection:update',
  CONNECTION_CONNECT: 'connection:connect',
  CONNECTION_DISCONNECT: 'connection:disconnect',
  REGISTER_WRITE: 'register:write',
  WORKSPACE_SAVE: 'workspace:save',
  WORKSPACE_LOAD: 'workspace:load',
  WORKSPACE_LIST: 'workspace:list',
  WORKSPACE_EXPORT: 'workspace:export',
  WORKSPACE_IMPORT: 'workspace:import',
  LOG_EXPORT: 'log:export',
  LOG_START: 'log:start',
  LOG_STOP: 'log:stop',
  SERIAL_PORTS_LIST: 'serial:ports-list',
  DIAGNOSTICS_RUN: 'diagnostics:run',
  POLL_RESULT: 'poll:result',
  CONNECTION_STATUS: 'connection:status',
  RAW_FRAME: 'raw:frame',
  LOG_ENTRY: 'log:entry',
  ALERT_FIRED: 'alert:fired',
} as const
